import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'




export const metadata: Metadata = {
  title: "TeeDee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body >
        {children}
        <Analytics/> 
      </body>
    </html>
    </ClerkProvider>
  );
}
